local UefBRNST2ADVBATTLESHIPproj = import('/mods/fa-total-mayhem/lua/TMprojectiles.lua').UefBRNST2ADVBATTLESHIPproj

---@class BRNST2ADVBATTLESHIPproj : UefBRNST2ADVBATTLESHIPproj
BRNST2ADVBATTLESHIPproj = Class(UefBRNST2ADVBATTLESHIPproj){}

TypeClass = BRNST2ADVBATTLESHIPproj
