local AeonBROST2ADVBATTLESHIPproj = import('/mods/fa-total-mayhem/lua/TMprojectiles.lua').AeonBROST2ADVBATTLESHIPproj

---@class BROST2ADVBATTLESHIPproj : AeonBROST2ADVBATTLESHIPproj
BROST2ADVBATTLESHIPproj = Class(AeonBROST2ADVBATTLESHIPproj){}

TypeClass = BROST2ADVBATTLESHIPproj
